import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { TournamentMatchesService } from './tournament-matches.service.js';
import { TournamentResultsService } from './tournament-results.service.js';
import { TournamentScheduleService } from './tournament-schedule.service.js';
import { JobMonitorService } from '../health/job-monitor.service.js';

/**
 * Runs every minute: generates brackets 2h before the start when nobody did
 * it by hand, puts tournaments live at their start time, lapses unanswered
 * time-change requests once a match
 * starts, and decides games whose evidence window closed (walkover / double
 * forfeit). Each step is idempotent, and overlapping runs are skipped.
 */
@Injectable()
export class TournamentDeadlinesService {
  private readonly logger = new Logger(TournamentDeadlinesService.name);
  private running = false;

  constructor(
    private readonly scheduleService: TournamentScheduleService,
    private readonly resultsService: TournamentResultsService,
    private readonly matchesService: TournamentMatchesService,
    private readonly monitor: JobMonitorService,
  ) {}

  @Cron(CronExpression.EVERY_MINUTE)
  async tick(): Promise<void> {
    if (this.running) return;
    this.running = true;
    try {
      const now = new Date();
      const { autoGenerated, started, expiredRequests, resolvedGames } = await this.monitor.run(
        'tournaments.deadlines',
        async () => ({
          autoGenerated: await this.matchesService.autoGenerateDue(now),
          started: await this.matchesService.startDueTournaments(now),
          expiredRequests: await this.scheduleService.expireStaleRequests(now),
          resolvedGames: await this.resultsService.resolveExpiredGames(now),
        }),
        (r) => `${r.autoGenerated} brackets, ${r.started} started, ${r.expiredRequests} time requests, ${r.resolvedGames} games`,
      );
      if (autoGenerated || started || expiredRequests || resolvedGames) {
        this.logger.log(
          `Auto-generated ${autoGenerated} bracket(s), started ${started} tournament(s), expired ${expiredRequests} time request(s), resolved ${resolvedGames} game(s)`,
        );
      }
    } catch (err) {
      this.logger.error('Tournament deadline job failed', err instanceof Error ? err.stack : err);
    } finally {
      this.running = false;
    }
  }
}
